services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  api:
    build:
      dockerfile: ./app/Dockerfile
    container_name: rag-api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    restart: unless-stopped

  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8501:8501"
    container_name: rag-frontend
    volumes:
      - ./frontend:/app

volumes:
  qdrant_data: