services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  # api:
  #   build: ./api
  #   container_name: rag-api
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - example=example
  #   depends_on:
  #     - qdrant

volumes:
  qdrant_data:

