services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: rag-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # TODO GITHUB ACTIONS SECRETS
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # TODO GITHUB ACTIONS SECRETS
      POSTGRES_DB: ${POSTGRES_DB} # TODO GITHUB ACTIONS SECRETS
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    image: ${DOCKERHUB_USERNAME}/portfolio-rag-mvp-api:latest
    container_name: rag-api
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    restart: unless-stopped

  frontend:
    image: ${DOCKERHUB_USERNAME}/portfolio-rag-mvp-frontend:latest
    container_name: rag-frontend
    ports:
      - "8501:8501"


volumes:
  qdrant_data:
  postgres_data:
