services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    ports:
      - "6333:6333"

  postgres:
    image: postgres:latest
    container_name: rag-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    ports: # TODO COMMENT OUT AFTER DB IS FILLED
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    image: ${DOCKERHUB_USERNAME}/portfolio-rag-mvp-api:latest
    container_name: rag-api
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_TOKEN_EXPIRE_MINUTES=${JWT_TOKEN_EXPIRE_MINUTES}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    restart: unless-stopped
    ports:
      - "8000:8000"

  frontend:
    image: ${DOCKERHUB_USERNAME}/portfolio-rag-mvp-frontend:latest
    container_name: rag-frontend
    ports:
      - "8501:8501"

volumes:
  qdrant_data:
  postgres_data:
